stages:
  - test
  - build

test-job:
  stage: test
  script:
    - apk add gcc python3-dev musl-dev linux-headers git
    - pip install --upgrade pip
    - pip install hatch
    - hatch shell
    - hatch test   
  tags: 
    - docker
