stages:
  - test

test-job:
  stage: test
  script:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)/src
    - apk add gcc python3-dev musl-dev linux-headers
    - pip install --upgrade pip
    - pip install hatch
    - pip install pytest pytest-cov
    - hatch test
    - pytest --cov=src.my_arithmetic_svalerio.__init__ --cov-report=xml --cov-report=term-missing 
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml 
  coverage: '/TOTAL.*? (\d+\%)$/'   
  tags: 
    - docker
